
name: Deploy Packages

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  dist-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: |
          version=$(echo ${{ github.ref_name }})
          if [[ "${version}" =~ ^v[0-9] ]]; then
            echo "using GitHub ref version ..."
            version=$(echo ${version} | sed 's/^v//')
            sed -i -e "s/^version = .*$/version = ${version}/" build.conf
          fi
          version=$(grep "^version = " build.conf | sed -e 's/^version = //')
          echo "configuring character generator version ${version} ..."
          echo "ver=${version}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo snap install --classic node
          npm install
          sudo python3 build.py init

      - name: Package Web
        run: python3 build.py dist-web

      - name: Package Desktop
        run: python3 build.py dist-desktop

      - name: Prepare Changes
        run: |
          python3 build.py -q print-changes > release_notes.tmp
          sed -i -e '1 s/^.*$/Changes:\n/' release_notes.tmp

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: 'Version ${{ env.ver }}'
          body_path: release_notes.tmp
          files: build/dist/*.zip
          prerelease: true
