
name: Build Distribution Packages

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  dist-packages:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: |
          version=$(echo ${{ github.ref_name }} | sed 's/^v//')
          # DEBUG:
          echo "Version: ${version}"
