
name: Deploy Page

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: |
          version=$(echo ${{ github.ref_name }})
          if [[ "${version}" =~ ^v[0-9] ]]; then
            echo "using GitHub ref version ..."
            version=$(echo ${version} | sed 's/^v//')
            sed -i -e "s/^version = .*$/version = ${version}/" build.conf
          fi
          version=$(grep "^version = " build.conf | sed -e 's/^version = //')
          echo "configuring character generator version ${version} ..."
          echo "ver=${version}" >> $GITHUB_ENV

      - name: Stage
        run: |
          python3 build.py -w stage-web
          sed -i -e "s/^config\[\"asset-info\"\] = \(.*\?\)\/master\//config\[\"asset-info\"\] = \1\/v${{ env.ver }}\//" build/web/script/config.js

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web/
