
name: Deploy Page

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stage
        run: |
          mkdir -p stage/
          cp -v index.html info.html LICENSE.txt stage/
          cp -vr assets/ data/ doc/ script/ stage/
          sed -i -e "s/\"asset-info\":\(.*\?\)\/master\//\"asset-info\":\1\/${{ github.ref_name }}\//" stage/script/config.js

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: stage/
