
name: Deploy Page

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stage
        run: |
          version=$(echo ${{ github.ref_name }} | sed 's/^v//')
          sed -i -e "s/^version = .*$/version = ${version}/" build.conf
          python3 build.py stage-web
          sed -i -e "s/\"asset-info\":\(.*\?\)\/master\//\"asset-info\":\1\/v${version}\//" build/web/script/config.js

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/stage/
