
name: Deploy Page

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      page: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
